branches:
  - v[0-9]+.[0-9]+.[0-9]+
  - main
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - verifyConditionsCmd: "~/.cargo/bin/semantic-release-rust verify-conditions"
      generateNotes: "cz bump --files-only"
      prepareCmd: "~/.cargo/bin/semantic-release-rust prepare ${nextRelease.version}"
      publishCmd: "~/.cargo/bin/semantic-release-rust publish"
  - - '@semantic-release/git'
    - assets: Cargo.toml
